### ISSUE TITLE
`ensuring` in ResultantMonad clashes with inbuild ensuring.

### ISSUE THREAD

**Issue by stephanh** [CommBank/omnitool#17]
Scala already has a method called `ensuring` with the whole implicit resolution this can cause clashes.

**Comment by stephanh** [comment]
I'm inclined to rename it to `ensure`.

**Comment by SamRoberts** [comment]
sounds good to me. I was thinking `disambiguatedEnsuringMethod`, but `ensure` seems a bit better. :smile:

**Comment by vineethvarghese** [comment]
:+1:
